---
- name: "create a backend directory"
  shell: mkdir $HOME/backend_unarchived

- name: store the files in the $HOME/ directory in the 'out' variable
  find:
    paths: $HOME/
  register: out

- debug:
      var: out

- name: store the files in the / directory in the 'out' variable
  find:
    paths: /
  register: out

- debug:
      var: out

- name: store the files in the ../../ directory in the 'out' variable
  find:
    paths: ../../
  register: out

- debug:
      var: out

- name: "Unarchive backend"
  unarchive:
    src: ../../../artifact.tar.gz
    dest: $HOME/backend_unarchived
    remote_src: yes

- name: "Run application"
  shell: |
      cd ~/backend_unarchived
      npm install
      pm2 stop default 
      pm2 start npm -- start