---
- name: "create a backend directory"
  shell: mkdir $HOME/backend_unarchived

- name: "Unarchive backend"
  unarchive:
    src: $HOME/../../artifact.tar.gz
    dest: $HOME/backend_unarchived
    remote_src: yes

- name: "Run application"
  shell: |
      cd ~/backend_unarchived
      npm install
      pm2 stop default 
      pm2 start npm -- start