---
- name: "create a backend directory"
  shell: mkdir $HOME/backend_unarchived

- name: "ls"
  shell: ls

- name: "ls 2"
  shell: ls ../../

- name: "ls 3"
  shell: ls ../../../../

- name: "Unarchive backend"
  unarchive:
    src: ../../../../artifact.tar.gz
    dest: $HOME/backend_unarchived
    remote_src: yes

- name: "Run application"
  shell: |
      cd ~/backend_unarchived
      npm install
      pm2 stop default 
      pm2 start npm -- start