---
- name: "Untar backend"
  command: |
    ls
    mkdir backend_unarchived
    cd backend_unarchived
    tar -tvf artifact.tar.gz
    ls

- name: "Run application with pm2"
  command: |
    cd backend_unarchived
    npm install
    pm2 stop default 
    pm2 start npm -- start