---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "stop pm2"
  become: true
  command: pm2 stop default

- name: "start pm2"
  become: true
  command: pm2 start npm -- start